### ISSUE TITLE
What are the FOV of Stereo?

### ISSUE THREAD

**Issue by monghimng** [argoai/argoverse-api#141]
Hi, I was looking for the FOVs for the camera images, but couldn't find any. I tried to compute them by ran into some weird values:

```
argoverse_loader = ArgoverseTrackingLoader(root_dir)
argoverse_loader.get_calibration("stereo_front_left").camera_config.intrinsic.astype(np.int32)
# prints
# array([[3666,    0, 1230,    0],
       [   0, 3666, 1059,    0],
       [   0,    0,    1,    0]], dtype=int32)
```

and

```
2 * np.arctan(1230 / 3666) / 3.14 * 180 = 37.113622213089016
```

I found it hard to believe the FOV is 37.113622213089016. Thanks.

**Comment by johnwlambert** [comment]
Hi @monghimng, thanks for your interest in our work. I believe the stereo FOV truly is around 37 degrees.

However, I would use half the [stereo image width](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/camera_stats.py#L12), instead of image plane origin offset:
```
2 * np.arctan(1232 / 3666) / 3.14 * 180
```
Note that the stereo camera has a very long focal length (3666) vs. ring camera focal length (1406) -- almost 3x as long. [Narrow f.o.v. is not unusual for long focal length cameras](https://en.wikipedia.org/wiki/Angle_of_view#Lens_types_and_effects).

Ring Camera horizontal f.o.v.:
```
2 * np.arctan(960 / 1406) / 3.14 * 180 = 68.68
```

We will confirm the stereo f.o.v. and get back to you.

**Comment by johnwlambert** [comment]
We can confirm that the stereo horizontal field of view is approximately 37 degrees.
