### ISSUE TITLE
Blurring procedure used for pedestrian faces

### ISSUE THREAD

**Issue by JustinLiang** [argoai/argoverse-api#162]
Hi,

We are interested in what blurring procedure you used for detecting and blurring the pedestrian faces. Is there code available to do this? Thanks!

**Comment by James-Hays** [comment]
Hi Justin!

We simply used open source code to detect faces and license plates. We used Tiny Faces ( https://github.com/peiyunh/tiny ) for faces and Anonymizer for license plates ( https://github.com/understand-ai/anonymizer ). They were configured to have pretty high recall, which means false positives, and indeed you can see blurred street signs or storefront logos in Argoverse just like you can in Google street view.

After using these packages, we manually inspected all frames to find things that we missed.

The blurring itself changed from Argoverse 1.0 to Argoverse 1.1. Argoverse 1.0 used a variable sized kernel which did a great job of seamlessly preserving privacy. But it had a large spatial extent and maybe blurred too much. Off the shelf pedestrian detectors worked poorly on the blurred data. In Argoverse 1.1 we simplified the blurring so that the blurred region is a 5x5 grid with each grid cell containing the average color. This way we could be more certain that the privacy was preserved, but also blur fewer pixels. 

Arguably, we should be doing privacy preserving face swapping instead of blurring, because the blurring pushes the faces off the natural image manifold. This makes it hard to detect faces for pretrained models, which isn't great, but there's also the possibility of detectors learning to find the privacy preservation artifacts and therefor doing better than they would on real data.

**Comment by johnwlambert** [comment]
Hi Justin, thanks again for your interest in our work. I'm closing this issue for now since we haven't heard back from you. Please feel free to re-open if you have additional questions.
