### ISSUE TITLE
Lane segment boundary definition

### ISSUE THREAD

**Issue by vadeshah** [argoai/argoverse-api#181]
I had a question regarding the left and right boundaries of each of the lane segments. Are these available as well-defined line objects in the dataset, or are they always approximated as 1.9 meters from the centerline, as described in the "centerline_to_polygon" function in utils/centerline_utils.py?

Oftentimes, when I visualize a series of parallel lane segments, it appears as if the lane segments are either overlapping, or do not make contact at all, which leads me to believe that the boundary data is not available. However, I would imagine that the lane boundaries might have been captured and processed using the LIDAR data, and I may simply be unable to find it in the Argoverse API. Any clarification on this would be greatly appreciated. Thank you in advance!

**Comment by johnwlambert** [comment]
Hi @vadeshah , thank you for your interest in our work. The Argoverse dataset maps include lane centerline annotations, rather than lane boundary annotations. In the `argoverse-api`, we provide some utilities to approximate lane segment polygons, given the centerline.

We provide a few more details in [our paper](https://arxiv.org/pdf/1911.02620.pdf): _"In our vector map, we offer lane centerlines, split into lane segments. We observe that vehicle trajectories generally follow the center of a lane so this is a useful prior for tracking and forecasting. We observe that in Miami, lane segments that could be used for route planning are on average 3.84 ±0.89 m wide. In Pittsburgh, the average width is 3.97 ±1.04 m."_

**Comment by vadeshah** [comment]
Thank you for your response! This is very helpful.
