### ISSUE TITLE
Access to only one lidar pointcloud

### ISSUE THREAD

**Issue by irenecortes** [argoai/argoverse-api#20]
Is it possible to access to only the upper or the lower lidar pointclouds? 
I have managed to calculate it, (the code is [here](https://github.com/irenecortes/argoverse_lidar)), but maybe there is an easier way...

**Comment by James-Hays** [comment]
Hi Irene,

That's very cool. We didn't disentangle the returns from the two lidars, but it looks like you've figured out a way to do it. Why did you want to use the lidars individually?

**Comment by irenecortes** [comment]
Hi James, 
I wanted to check how it would affect the performance of some algorithms trained with the KITTI dataset if I change the LiDAR model. I thought the upper LiDAR could be interesting to try because the position of the lower one it's more unusual.

**Comment by janesjanes** [comment]
We don't have information on which point belong to which lidar specifically, but yeah you can probably make some inference :) 

But even with one lidar I think it would still be quite different than Kitti because we are using different lidar model. Would be cool to see how that effect performance,

I'll go ahead and close this issue then,
