### ISSUE TITLE
Convert Argoverse HD maps to OSM format

### ISSUE THREAD

**Issue by lioutasb** [argoai/argoverse-api#202]
I would like to load the Argoverse HD maps with lanelet2 so I was hoping if there is an easy way of converting the map files to proper "OpenStreetMaps" format.

**Comment by johnwlambert** [comment]
Hi @lioutasb, thanks for your interest in our work. When we released Argoverse 1.0, OpenStreetMaps did not support lane-level geometry. Instead, it modeled road infrastructure as road-level geometry. This may have since changed, although I doubt it.

Could you share an example Lanelet2 file that you are working with?

**Comment by benjaminrwilson** [comment]
Closed due to inactivity. @lioutasb, please open another issue if necessary.
