### ISSUE TITLE
Problematic "render_bev_labels_mpl" function

### ISSUE THREAD

**Issue by richardkxu** [argoai/argoverse-api#38]
First of all, thank you very much for providing this amazing dataset api! It makes autonomous driving research much easier. 
However, I noticed several potential problems with the following function: `render_bev_labels_mpl` inside `argoverse-api/demo_usage/visualize_30hz_benchmark_data_on_map.py`:

1. It seems like by passing "city axis" in the argument, the function gives me "ego coordinates". Passing "ego axis" gives me city coordinates. This can be illustrated by leaving only the lidar bev plotting part of the code and comment everything out:
Plotting Lidar in ego axis:
![lidar_ego0](https://user-images.githubusercontent.com/25449141/61924546-ea409180-af2d-11e9-8897-c6b308531a43.jpg)

Plotting Lidar in city axis:
![lidar_city0](https://user-images.githubusercontent.com/25449141/61924555-f3c9f980-af2d-11e9-9183-94b3187f89e8.jpg)
Visually, the 2nd one looks more like in ego coord.

2. Whenever I plot driveable area (da) and lane polygons in "ego axis", all the da and polygon disappear, leaving me a blank plot. This can be illustrated by leaving only the da and polygon part of the code and comment everything else:

Plotting da and polygon in ego axis:
![lane_ego0](https://user-images.githubusercontent.com/25449141/61924648-663ad980-af2e-11e9-9e06-57aea8ff008e.jpg)
Plotting da and polygon in city axis (This seems to work. But again this looks more like in ego coord):

![lane_city0](https://user-images.githubusercontent.com/25449141/61924667-794da980-af2e-11e9-9e9d-47e97b7f48df.jpg)

3. In the current implementation, lidar bev is always bundled with "ego axis" so that you have to plot lidar in "ego axis". In "city axis", you do not have the option to even plot lidar. I think it would be great to give user the choice to choose whether or not to include lidar bev in the plot.

For my research, I try to generate driveable area and lane line on the map in ego coordinates for every frame in every log. I spent 2 days try to debug but could not figure it out. If you can take a look, it would be very helpful! I really appreciate it!

**Comment by johnwlambert** [comment]
Hi @richardkxu, good question. Let me try to answer. Let's look at the [Map Tutorial notebook](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb).

There are 4 plots here, each rendered with the `render_bev_labels_mpl` function. 
- The first plot is called with `"city_axis"`, and the axes show an x-axis range from [2520,2660] and y-axis range from [1140, 1280] meters.
- The second plot, third, and fourth plots are called with the `""ego_axis"` flag and show x-axis and y-axis ranges of [-80,80] and [-80,80] meters.

In L220 of [demo_usage/visualize_30hz_benchmark_data_on_map.py](https://github.com/argoai/argoverse-api/blob/master/demo_usage/visualize_30hz_benchmark_data_on_map.py#L220), if the desired rendering coordinate system is not the city ref. system, we bring the local driveable area boundaries (`local_da`) from the city coordinate system into the egovehicle coordinate system with 
`egoframe_local_da = city_to_egovehicle_se3.inverse_transform_point_cloud(local_da)`, 
which is equivalent to using the inverse:
`egoframe_local_da = city_se3_egovehicle.inverse().transform_point_cloud(local_da)`
or to 
`egoframe_local_da = egovehicle_se3_city.transform_point_cloud(local_da)`

We also bring the lane polygons into the egovehicle frame in such a case (L254):
` local_lane_polygon = city_to_egovehicle_se3.inverse_transform_point_cloud(local_lane_polygon)`

Otherwise, we leave all points in the city frame and would have passed in LiDAR points living in the city frame to the `render_bev_labels_mpl` function.

**Comment by johnwlambert** [comment]
@richardkxu It wouldn't be possible to know which absolute frame the points are living in by looking only at their relative positions to each other. Furthermore, since we can bring the map into the egovehicle frame, or the egovehicle-gathered data into the map frame, this also won't tell us the absolute frame we are rendering the points in.

I think your best bet is to look at the map tutorial notebook again carefully and look at your point coordinate values -- if they are in the [0,5000] range, you are usually in city coordinates. If they are in [-200,200], you are usually in egovehicle frame coordinates.

**Comment by richardkxu** [comment]
Thanks for the quick respond! I am able to render the lane and driveable area polygons by setting the search and plotting limit to [-200, 200].

However, it seems like even in ego coord, the lane and driveable area polygons are not align with the vehicle's pointing direction. I am not sure if this is just a design choice? I align them by rotating the rendered image by -yaw degrees of the vehicle pose. I wonder if there is a better way to do it?

**Comment by johnwlambert** [comment]
Hi @richardkxu, there are many choices on how to rotate the frame, I don't think one is necessarily better. I chose to align the ego-frames to the city frame, so that it would be easy to see them stacked horizontally,  as shown below:
![PIT_f0826a9f-f46e-3c27-97af-87a77f7899cd_315979566219959000 (2)](https://user-images.githubusercontent.com/16724970/62384450-4e072380-b507-11e9-95bc-a8940960da3e.png)
In this scheme, we use the North-South orientation (+y is north, +x is east) 

As you mentioned, you could also align them so that the egovehicle always points in the direction of the x axis.

**Comment by johnwlambert** [comment]
@richardkxu Do you still have any questions about the function?

Another way to think about this:
We render the dynamic egovehicle moving around in the fixed world.

You're interested in rendering the world moving around the egovehicle.
