### ISSUE TITLE
Questions on coordinate transform

### ISSUE THREAD

**Issue by richardkxu** [argoai/argoverse-api#39]
Hi, thanks for this amazing dataset api! While using the API, I have a few coordinate transform related questions:

1. I am very confused on which of the following raw data are in city coord and which are in ego coord: lidar pointcloud, ground truth 2D/3D bboxes, driveable area and lane polygons.
2. Which function should I use to convert driveable area and lane polygons to city coord? And which function to use to convert them to ego coord?
3. What is SE3 transform? It is for city->ego transform or ego->city?

If you can take a look, it would be awesome. Thanks!

**Comment by johnwlambert** [comment]
Hi @richardkxu, the pose files (e.g. `argoverse-tracking/train1/84c35ea7-1a99-3a0c-a3ea-c5915d68acbc/poses/city_SE3_egovehicle_315969518071010056.json`) represent a transformation from the egovehicle frame into the city frame.

We use this order because $$pt_{city} = {}^{city} T_{egovehicle} p_{egovehicle}$$

**Comment by johnwlambert** [comment]
Any map elements (driveable area, lane centerlines, hallucinated lane polygons) are provided in the  city coordinate system. 

If you haven't had a chance to read it yet, I think Section 1 of our Supplementary Material ([linked here](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf)) would help clarify things a bit.

We provide a class that represents an SE(3) transform (https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/se3.py#L7) and it is not limited to transformations between any specific coordinate systems. It can be used for any 6 dof transformation in 3 dimensions.

For an example of bringing LiDAR points in the egovehicle frame into the city coordinate system, you will want to use
```python
city_to_egovehicle_se3 = SE3(rotation=pose_city_to_ego["rotation"], translation=ego_center_xyz)
city_points = city_to_egovehicle_se3.transform_point_cloud(egovehicle_pts)
```
(an example is in `visualize_30hz_benchmark_data_on_map.py` [here](https://github.com/argoai/argoverse-api/blob/master/demo_usage/visualize_30hz_benchmark_data_on_map.py#L172)

If you want to bring a point cloud, polygon, or polyline (like a line centerline or lane polygon) from the city coordinate system, into the egovehicle coordinate system, you will just form the inverse of that same SE3 and transform the points as above:
```python
city_to_egovehicle_se3 = SE3(rotation=pose_city_to_ego["rotation"], translation=ego_center_xyz)
egovehicle_to_city_se3 = city_to_egovehicle_se3.inverse()
egovehicle_pts = egovehicle_to_city_se3.transform_point_cloud(city_points)
```

**Comment by richardkxu** [comment]
Got it! Thank you!

**Comment by CoderChen01** [comment]
Hello, thank you beyond words for your work, I have a few similar questions:
* What is a city coordinate system and how does it define it?
* What is the `SE3`? Is it your own definition or is it a standard? What's its full name?

Looking forward to your reply, thank you very much.

**Comment by CoderChen01** [comment]
More specifically, can city coordinates be understood as world coordinates?
Is the X0Y plane in the city coordinate system on the ground?

**Comment by CoderChen01** [comment]
@johnwlambert

**Comment by johnwlambert** [comment]
Hi @CoderChen01, thanks for your interest in our work.

If you haven't had a chance to read it yet, I think Section 1 of our Supplementary Material ([linked here](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf)) would help clarify things a bit.

<img width="860" alt="Screen Shot 2021-08-13 at 7 47 58 PM" src="https://user-images.githubusercontent.com/16724970/129427640-c5133818-b67a-48e0-8e57-4be959d2732e.png">

The city coordinate frame can be understood as our "world" / "global" frame, although we prefer the term "city", since Argoverse 1.1. maps are only defined at the city level. Indeed, +z is roughly the negative gravity vector in the city coordinate system.

SE(3) transformations are frequently used in robotics/ computer vision. Nice references by Ethan Eade can be found [here](http://ethaneade.com/lie_groups.pdf) in Section 9, page 11 of  or [here](http://ethaneade.com/lie.pdf) in Section 3, page 8.

Our [`SE3` class](https://github.com/argoai/argoverse-api/blob/master/argoverse/utils/se3.py) is roughly equivalent to the Pose3 class in [GTSAM](https://github.com/borglab/gtsam/blob/develop/gtsam/geometry/Pose3.h), if you're familiar with that library.

**Comment by CoderChen01** [comment]
I got it. Thank you for your answer.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John ***@***.***&gt;; 
发送时间: 2021年8月14日(星期六) 上午7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [argoai/argoverse-api] Questions on coordinate transform (#39)





 
Hi @CoderChen01, thanks for your interest in our work.
 
If you haven't had a chance to read it yet, I think Section 1 of our Supplementary Material (linked here) would help clarify things a bit.
 

 
The city coordinate frame can be understood as our "world" / "global" frame, although we prefer the term "city", since Argoverse 1.1. maps are only defined at the city level. Indeed, +z is roughly the negative gravity vector in the city coordinate system.
 
SE(3) transformations are frequently used in robotics/ computer vision. Nice references by Ethan Eade can be found here in Section 9, page 11 of  or here in Section 3, page 8.
 
Our SE3 class is roughly equivalent to the Pose3 class in GTSAM, if you're familiar with that library.

**Comment by MVSolInc** [comment]
I am looking for Camera Height from the ground plane. 
I am also looking for Vehicle Pitch information.
