### ISSUE TITLE
self.get_lane_ids_in_xy_bbox() function?

### ISSUE THREAD

**Issue by kecaiwu** [argoai/argoverse-api#44]
why the self.get_lane_ids_in_xy_bbox() function returns a list that means the lane id? I think the lane segment should have an unique id? For example, in the get_lane_segment_predecessor_ids() function, the input args lane_segment_id is a int type. THX.

**Comment by johnwlambert** [comment]
Hi @kecaiwu, let me try to clarify the functionality of `argoverse_map.get_lane_ids_in_xy_bbox(query_x, query_y, city_name, query_search_range_manhattan)` ([code here](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_api.py#L577)). Suppose you are looking at a point (1000,2000) in the map in Pittsburgh. Suppose you wish to find all lanes that live within a 50x50 square, centered at this query point. You would find all lane IDs that live from (975,1975) to (1025,2025). We consider this as searching in a ball under the L1 norm (manhattan distance).

**Comment by kecaiwu** [comment]
Hi @johnwlambert, thank for help. I had understood the function of `argoverse_map.get_lane_ids_in_xy_bbox()`. If I want to know the current lane segment of self vehicle,   So I set the square is 0.1x0.1, however, the function still returns two land id. Or, how to find the current lane id of the self vehicle?

**Comment by johnwlambert** [comment]
Hello @kecaiwu, I see, thanks for the clarification. A good option to use is:

```python
def get_nearest_centerline(
        self, query_xy_city_coords: np.ndarray, city_name: str, visualize: bool = False
    ) -> Tuple[LaneSegment, float, np.ndarray]:
```

[code](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_api.py#L448).

This is an approximation for graph localization -- just look for the closest lane centerline waypoint.

We have to resort to approximations because exact graph localization is often impossible. For example, if you find yourself in a complex intersection (see below), 3 centerlines sometimes cross at the same 3d point. We can't know exactly which centerline to follow. 

<img width="253" alt="Screen Shot 2019-08-06 at 12 26 58 AM" src="https://user-images.githubusercontent.com/16724970/62519741-0cb19500-b7e1-11e9-8778-cc4104204907.png">
(from [Figure 1 of the Supplemental Material](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Chang_Argoverse_3D_Tracking_CVPR_2019_supplemental.pdf).)

Reasoning about the prior trajectory can help.
