### ISSUE TITLE
How to transform coordinate from city to ego vehicle in forecasting dataset?

### ISSUE THREAD

**Issue by kecaiwu** [argoai/argoverse-api#45]
I had know transform the coordinate from city to ego vehicle in tracking dataset. However, How to transform coordinate from city to ego vehicle in forecasting dataset? THX

**Comment by kecaiwu** [comment]
'city_to_egovehicle_se3 = SE3(rotation=pose_city_to_ego["rotation"], translation=pose_city_to_ego["translation"])
egovehicle_to_city_se3 = city_to_egovehicle_se3.inverse()
egovehicle_pts = egovehicle_to_city_se3.transform_point_cloud(polygon)'

In the forecasting dataset, I have no idea about the self vehicle pose.

I want to convert the forecasting dataset to the RGB image based on self vehicle location.

**Comment by kecaiwu** [comment]
I can compute the rotation and translation matrix by the city coordinate to self vehicle coordinate, this is the right approach?

**Comment by sujithvemi** [comment]
@kecaiwu I think you are right as in SE3 we take the co-ordinates of lidar sensor to transform from city to ego vehicle. Thus, in forecasting, if you assume the origin is at the location of "AGENT" specified in forecasting dataset, you can just compute the transformation according to that.

But I would urge you to think whether that is the best frame of reference to be used for the problem of forecasting. Because if you are trying to capture the interactions between vehicles that are not in direct correlation with our "AGENT", there can be spurious correlations.

**Comment by kecaiwu** [comment]
Hi @sujithvemi, thank for your reply. Because of the "AGENT" doesn't know which vehicles around the environment will direct influence he actions. So, we should think all dynamic objects are equal, this idea is right?
By the way, I do not only predict the trajectory of "AGENT" in our forecasting dataset. I want to training a self-driving vehicle by using the elements in the forecasting dataset. This idea is from the waymo paper"chauffeurnet-learning-to-drive-by-imitating-the-best-and-synthesizing-the-worst".
Do you have the plan to provide the classes of all objects in the forecasting dataset? For example, the vehicle, pedestrian, or cyclist.

**Comment by sujithvemi** [comment]
Hi @kecaiwu, yes, I was also talking about treating all dynamic objects as equal to model the interactions. I am not any expert though, so take that advice with a pinch of salt.

I am not a contributor so I don't know about their plans.

**Comment by janesjanes** [comment]
Hi @kecaiwu 
Even if you have the ego centric coordinate, you wouldn't be able to map to image since we didn't provide image for the forecasting dataset,

As for the transformation, sure, I guess you could (roughly) infer from the agent location and direction, but I agree with @sujithvemi I don't really see the benefit of converting to ego centric in forecasting scenario.

We don't have any plan to release the class info in forecasting dataset yet, but it's good to know that there's a demand for it. We'll keep that in mind.

**Comment by kecaiwu** [comment]
Hi @sujithvemi @janesjanes, thank for your help, I will check my idea again.

**Comment by DKandrew** [comment]
> Hi @kecaiwu
> Even if you have the ego centric coordinate, you wouldn't be able to map to image since we didn't provide image for the forecasting dataset,
> 
> As for the transformation, sure, I guess you could (roughly) infer from the agent location and direction, but I agree with @sujithvemi I don't really see the benefit of converting to ego centric in forecasting scenario.
> 
> We don't have any plan to release the class info in forecasting dataset yet, but it's good to know that there's a demand for it. We'll keep that in mind.

Hi @janesjanes , I would also like to have image, lidar, and pose information in the forecast dataset as well~
